#!/usr/bin/env bash
# Distribute the library to pypi.org.

# Delete dist directory to ensure a clean build
rm -r dist

python -m build

python -m twine upload dist/*
# python -m twine upload --repository testpypi dist/*
