#!/usr/bin/env bash
# Distribute the library to pypi.org.

# Delete dist directory to ensure a clean build
rm -r dist

python3 -m build

python3 -m twine upload dist/*
# python3 -m twine upload --repository testpypi dist/*
