#!/usr/bin/env bash
# Setup the dependencies.

# Stop on errors
set -e

# Runtime dependencies
python -m pip install -r requirements.txt

# Test dependencies
python -m pip install -r requirements-test.txt

# Tools for distribution to pypi.org
python -m pip install --upgrade build
python -m pip install --upgrade twine
